FROM ubuntu:14.04
MAINTAINER Zhaowen Zou <zwzou@ucsd.edu>
RUN apt-get update && \
	apt-get -y upgrade && \
	apt-get install -y build-essential && \
	apt-get install -y software-properties-common && \
	apt-get install -y curl git unzip vim man wget 
CMD ["bash"]

